export const FETCH_USER = 'FETCH_USER'

export const FETCH_PUBLIC_STORIES_START = 'FETCH_PUBLIC_STORIES_START'
export const FETCH_PUBLIC_STORIES = 'FETCH_PUBLIC_STORIES'
export const FETCH_MY_STORIES = 'FETCH_MY_STORIES'
export const SUBMIT_STORY = 'SUBMIT_STORY'